version: '3.4'

services:
  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: p4ssw0rD
    ports:
      - 2433:1433
    volumes:
      - "mssql-server:/var/opt/mssql"
  adminer:
    image: adminer:4.8.1
    ports:
      - 2431:8080
    environment:
      TZ: Europe/Rome
      ADMINER_DEFAULT_SERVER: mssql-server

  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:3.9.0'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:3.1.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=host.docker.internal:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
      
  unipr-anagrafiche:
    image: ghcr.io/toooomm/unipr-anagrafiche:latest
    pull_policy: always
    depends_on:
      - mssql-server
    environment:
      TZ: Europe/Rome
    volumes:
      - "./config/unipr-anagrafiche-appsettings.json:/app/appsettings.json:ro"
      
  unipr-imu:
    image: ghcr.io/toooomm/unipr-imu:latest
    pull_policy: always
    depends_on:
      - mssql-server
      - kafka
    environment:
      TZ: Europe/Rome
    volumes:
      - "./config/unipr-imu-appsettings.json:/app/appsettings.json:ro"
      
  unipr-pagamenti:
    image: ghcr.io/toooomm/unipr-pagamenti:latest
    pull_policy: always
    depends_on:
      - mssql-server
      - kafka
    environment:
      TZ: Europe/Rome
    volumes:
      - "./config/unipr-pagamenti-appsettings.json:/app/appsettings.json:ro"

volumes:
  mssql-server: